services:
  frontend:
    build:
      context: ./interncomp-frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./interncomp-frontend:/app
      - /app/node_modules # Avoid overwriting node_modules
    ports:
      - '4000:4000' # Frontend is being set at port 4000 in vite.config.js
    networks:
      - app-network

  db:
    container_name: pg_db
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: interncomp-database
    ports:
      - '5433:5432' # Map some automatically chosen machine port to container's PostgreSQL port 5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

  backend:
    build:
      context: ./interncomp-backend
      dockerfile: Dockerfile.dev
    depends_on:
      - db
    volumes:
      - ./interncomp-backend:/app
      - /app/node_modules # Avoid overwriting node_modules
    ports:
      - '3000:3000' # Map backend container's port 3000 to local port 3000
    env_file:
      - ./interncomp-backend/.env
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  pgdata: