services:
  frontend:
    build:
      context: ./interncomp-frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./interncomp-frontend:/app
      - /app/node_modules # Avoid overwriting node_modules
    ports:
      - '5173:5173' # Vite default port
    networks:
      - app-network

  # backend:
  #   build:
  #     context: ./interncomp-backend
  #     dockerfile: Dockerfile.dev
  #   volumes:
  #     - ./interncomp-backend:/app
  #     - /app/node_modules # Avoid overwriting node_modules
  #   ports:
  #     - '4000:3000' # Map backend container's port 3000 to local port 4000
  #   depends_on:
  #     - db
  #   environment:
  #     DATABASE_URL: postgres://postgres:password@db:5432/interncomp-database
  #   networks:
  #     - app-network

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: interncomp-database
    ports:
      - '5432' # Map some automatically chosen machine port to container's PostgreSQL port 5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  pgdata: